# Generated by Django 5.0.14 on 2026-06-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybible', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='timeline_events',
            field=models.ManyToManyField(blank=True, related_name='scenes', to='storybible.timelineevent'),
        ),
    ]
