# Generated by Django 5.0.14 on 2026-06-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybible', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_word_goal',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_word_goal',
            field=models.BooleanField(default=False),
        ),
    ]
