# Generated by Django 5.0.14 on 2026-06-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybible', '0004_userprofile_daily_word_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
