# Generated by Django 5.0.14 on 2026-06-27 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybible', '0006_project_cover_image_project_genre_project_synopsis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('group_type', models.CharField(blank=True, help_text='e.g. Faction, Organization, Guild, Family, Religion', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='storybible.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='scene',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='scenes', to='storybible.group'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(blank=True, help_text='e.g. Weapon, Artifact, Relic, Tool, MacGuffin', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='storybible.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='scene',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='scenes', to='storybible.item'),
        ),
        migrations.CreateModel(
            name='Lore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('lore_type', models.CharField(blank=True, help_text='e.g. Magic System, Religion, Language, History, Law, Geography', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lore', to='storybible.project')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='scene',
            name='lore',
            field=models.ManyToManyField(blank=True, related_name='scenes', to='storybible.lore'),
        ),
    ]
