# Generated by Django 5.0.14 on 2026-06-28 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybible', '0007_group_scene_groups_item_scene_items_lore_scene_lore'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('note_type', models.CharField(choices=[('general', 'General'), ('todo', 'To-Do'), ('research', 'Research'), ('warning', 'Warning'), ('idea', 'Idea')], default='general', max_length=20)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='storybible.scene')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
