# Generated by Django 5.0.14 on 2026-06-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybible', '0008_scenenote'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['project', 'scene'], name='storybible__project_0de2ef_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='storybible__convers_56c0a1_idx'),
        ),
        migrations.AddIndex(
            model_name='scene',
            index=models.Index(fields=['project', 'order'], name='storybible__project_e02a03_idx'),
        ),
        migrations.AddIndex(
            model_name='scene',
            index=models.Index(fields=['project'], name='storybible__project_0cd430_idx'),
        ),
        migrations.AddIndex(
            model_name='scenenote',
            index=models.Index(fields=['scene', 'resolved'], name='storybible__scene_i_85187d_idx'),
        ),
        migrations.AddIndex(
            model_name='sceneversion',
            index=models.Index(fields=['scene', '-created_at'], name='storybible__scene_i_d13020_idx'),
        ),
    ]
